"""extend vulnerabilities with CVE CWE CVSS intelligence

Revision ID: 0e9af7802149
Revises: 14dfb792d525
Create Date: 2026-09-03 21:00:32.861549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e9af7802149'
down_revision: Union[str, Sequence[str], None] = '14dfb792d525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vulnerabilities', sa.Column('cve_id', sa.String(length=50), nullable=True))
    op.add_column('vulnerabilities', sa.Column('cwe_id', sa.String(length=50), nullable=True))
    op.add_column('vulnerabilities', sa.Column('cvss_score', sa.Float(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('cvss_vector', sa.String(length=200), nullable=True))
    op.add_column('vulnerabilities', sa.Column('confidence', sa.String(length=20), nullable=True))
    op.add_column('vulnerabilities', sa.Column('category', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_vulnerabilities_cve_id'), 'vulnerabilities', ['cve_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerabilities_cve_id'), table_name='vulnerabilities')
    op.drop_column('vulnerabilities', 'category')
    op.drop_column('vulnerabilities', 'confidence')
    op.drop_column('vulnerabilities', 'cvss_vector')
    op.drop_column('vulnerabilities', 'cvss_score')
    op.drop_column('vulnerabilities', 'cwe_id')
    op.drop_column('vulnerabilities', 'cve_id')
    # ### end Alembic commands ###
