"""add device telemetry and security events tables

Revision ID: 14dfb792d525
Revises: 1c702225ec30
Create Date: 2026-09-03 20:29:04.465264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14dfb792d525'
down_revision: Union[str, Sequence[str], None] = '1c702225ec30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_telemetry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('telemetry_version', sa.String(length=20), nullable=False),
    sa.Column('agent_version', sa.String(length=50), nullable=True),
    sa.Column('cpu_usage_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('memory_total_mb', sa.Integer(), nullable=True),
    sa.Column('memory_used_mb', sa.Integer(), nullable=True),
    sa.Column('memory_usage_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('disk_total_gb', sa.Integer(), nullable=True),
    sa.Column('disk_used_gb', sa.Integer(), nullable=True),
    sa.Column('disk_usage_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('network_interfaces', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active_connections', sa.Integer(), nullable=True),
    sa.Column('firewall_enabled', sa.Boolean(), nullable=True),
    sa.Column('antivirus_enabled', sa.Boolean(), nullable=True),
    sa.Column('os_updates_pending', sa.Integer(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_telemetry_collected_at'), 'device_telemetry', ['collected_at'], unique=False)
    op.create_index(op.f('ix_device_telemetry_device_id'), 'device_telemetry', ['device_id'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detection_source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_detected_at'), 'security_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_security_events_device_id'), 'security_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_security_events_event_type'), 'security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_events_severity'), 'security_events', ['severity'], unique=False)
    op.create_index(op.f('ix_security_events_status'), 'security_events', ['status'], unique=False)
    op.alter_column('audit_logs', 'result',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'result',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'success'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_security_events_status'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_severity'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_type'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_device_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_detected_at'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_device_telemetry_device_id'), table_name='device_telemetry')
    op.drop_index(op.f('ix_device_telemetry_collected_at'), table_name='device_telemetry')
    op.drop_table('device_telemetry')
    # ### end Alembic commands ###
